run:
  timeout: 3m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - gosimple
    - unused
    - typecheck
    - gocritic

issues:
  max-same-issues: 0
  max-issues-per-linter: 0

