# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X main.version={{.Version}}
archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  abbrev: -1
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

  groups:
    - title: "BREAKING // ICE BREACH"
      regexp: '^.*?(feat|feature|fix|refactor|perf|deps)(\([[:word:]-]+\))?!:.+$'
      order: 0

    - title: "FEATURES // new mods"
      regexp: '^.*?(feat|feature)(\([[:word:]-]+\))?!?:.+$'
      order: 10

    - title: "FIXES // patch run"
      regexp: '^.*?fix(\([[:word:]-]+\))?!?:.+$'
      order: 20

    - title: "REFACTOR // rewired circuits"
      regexp: '^.*?refactor(\([[:word:]-]+\))?!?:.+$'
      order: 30

    - title: "DEPS // supply chain"
      regexp: '^.*?(deps(\([[:word:]-]+\))?!?:.+|Bump .+)$'
      order: 40

    - title: "OTHER // static"
      order: 999

release:
  mode: replace
  header: |
    ## GHOST {{ .Tag }} // UPLINK ONLINE
    _Delta: {{ .PreviousTag }} → {{ .Tag }}_
  footer: |
    ---
    **Full Changelog**: https://github.com/theantichris/ghost/compare/{{ .PreviousTag }}...{{ .Tag }}

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
